### PR TITLE
#87 attempt two tests for codes

### PR DESCRIPTION
**Pull request by OzYossarian**

### CODE REVIEW

**Comment by peter-janderks** [comment]
Did something go wrong with pushing the files in the tests/end_to_end directory?

**Comment by OzYossarian** [comment]
Ah yes perhaps? The end to end tests for ToricColourCode and TriangularColourCode should be blank - they're just placeholders to remind me of which four codes to write end to end tests for. But their names should start with `test_` so they test runner finds them!

**Comment by OzYossarian** [comment]
Was there something else that looked wrong in that directory?

**Comment by peter-janderks** [comment]
looks good :+1:

**Pull request merged**
