### PR TITLE
#104 more tests for compiler

### PR DESCRIPTION
**Pull request by peter-janderks**

### CODE REVIEW

**Comment by OzYossarian** [comment]
I don't know about merging this directly into dev - I'll merge it into the branch it was created from

**Comment by OzYossarian** [comment]
Actually having had a look, all the branches underneath have been merged into dev I think! So can do this merge, but note that we're only halfway through writing the tests for the compiler. Merging now is still probably a good idea though, because the changes to make Kandel compatible with Python 3.9 are in here too.

**Review by OzYossarian — COMMENTED** [review]
I've reviewed your bits - all looks good (from what I understand! The docs stuff is beyond me atm). Once you've given my bits the thumbs up, we can merge.

**Comment by peter-janderks** [comment]
Everything looks good and tox passed on my device. I added some docstrings for the Compiler class. LGTM!

**Comment by OzYossarian** [comment]
I can't seem to resolve these conflicts...

**Review by OzYossarian — APPROVED** [review]
LGTM!

**Comment by peter-janderks** [comment]
Looks good to me and running tox with python 3.9 is working on my device.

**Pull request merged**
